### ISSUE TITLE
Make compatible to latest three.js version

### ISSUE THREAD

**Issue by wirmachenbunt** [sjpt/metaballsWebgl#1]
any idea how to make this compatible to the latest three.js version

and add a export in order to easily import this into an existing three.js project ?

any ideas regarding compability are welcome

**Comment by sjpt** [comment]
I'll have a look; certainly time I updated lots of my myriad
antediluvian code.
It probably won't be that soon I'm afraid.

**Comment by sjpt** [comment]
I've gone a little part of the way; it is now using the lastest revision of three.js.
Moving to 'proper' modules will take me a little longer as I need to restructure another much bigger project (CSynth)

Apart from being able to use the module version of three there was only one small change needed for breaking changes to three, to change light intensity.

**Comment by wirmachenbunt** [comment]
is it still using a custom version of three or does the latest three version just works out of the box with your code ?

thanks for taking the time

**Comment by sjpt** [comment]
It isn't a custom version of three.
It is however renamed with an explicit revision number and included within
the project
to reduce the risk of breaking changes to three.js breaking it.

**Comment by wirmachenbunt** [comment]
thanks for the info and thanks for the support. :D
